---
name: automerge
"on":
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: paulte/automerge-action@3e403867f080d030b1a45b929420b35b4143be63 # main
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
