---
name: automerge
"on":
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: paulte/automerge-action@c8acbd33d6d14ac8d2eb13b6c8c59a9f4d5632b1 # main
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
